image: java:8

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    TERM: "dumb"

before_script:
    - chmod +x gradlew

stages:
  - build

build:
  stage: build
  script:
    - sed -i " 1 s/.*/&-b${CI_JOB_ID}/" version
    - ./gradlew -g /cache/.gradle clean build jacocoTestReport dist
  artifacts:
    paths:
    - build/jadx*.zip
