language: java
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk6

before_install:
    - chmod +x gradlew

script:
    - TERM=dumb ./gradlew clean build dist

after_success:
    - TERM=dumb ./gradlew jacocoTestReport coveralls

sudo: false

cache:
    directories:
        - $HOME/.gradle

notifications:
    email:
        - skylot@gmail.com
