language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6

before_install:
    - chmod +x gradlew

script:
    - TERM=dumb ./gradlew clean build dist

after_success:
    - TERM=dumb ./gradlew jacocoTestReport coveralls

notifications:
    email:
        - skylot@gmail.com
