language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6
env:
    - TERM=dumb

before_install:
    - chmod +x gradlew

script:
    - ./gradlew clean build dist

after_success:
    - ./gradlew jacocoTestReport coveralls

notifications:
    email:
        - skylot@gmail.com
